version: '3.1'
services:
  keycloak:
    build: .
    image: "adorsys/sts-keycloak:latest"
    environment:
      SSO_ADMIN_USERNAME: admin
      SSO_ADMIN_PASSWORD: admin123
    ports:
    - "8080:8080"
    - "8787:8787"
    links:
    - sts
  post_process:
    image: adorsys/keycloak-config-cli:v0.1.0-3-2.5.5
    depends_on:
    - keycloak
    links:
    - keycloak
    volumes:
    - ./config:/opt/keycloak-config-cli/configs
    environment:
    - KEYCLOAK_URL=http://keycloak:8080/auth
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin123
  sts:
    image: "adorsys/sts-example:latest"
    ports:
    - "8888:8888"
