version: '3.1'
services:
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
#    volumes:
#    - "./.docker/postgres/data:/var/lib/postgresql/data"
  keycloak:
    build: .
    image: "adorsys/sts-keycloak:${project.version}-keycloak-${keycloak.version}"
    environment:
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_USER: admin
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_PORT_5432_TCP_ADDR: postgres
    ports:
    - "8080:8080"
    - "8787:8787"
    volumes:
    - "./.docker/keycloak/data:/opt/jboss/keycloak/standalone/data"
    links:
    - postgres
    command:
    - "-b"
    - "0.0.0.0"
    - "--debug"
