browserFlow: ad browser
directGrantFlow: ad direct grant
flows:
  - modelAlias: browser
    alias: ad browser
    executions:
      - alias: ad browser forms
        executions:
        - modelProvider: auth-username-password-form
          provider: custom-auth-username-password-form
          displayName: Custom Username Password Form
  - modelAlias: direct grant
    alias: ad direct grant
    executions:
      - modelProvider: direct-grant-validate-password
        provider: custom-direct-access-authenticator
        displayName: Custom Password Validate
